// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./../components/Breadcrumbs.vue')['default']
    ClustersTable: typeof import('./../components/clustering/ClustersTable.vue')['default']
    ClusterTags: typeof import('./../components/clustering/ClusterTags.vue')['default']
    CompareCard: typeof import('./../components/CompareCard.vue')['default']
    FileTimestamp: typeof import('./../components/FileTimestamp.vue')['default']
    Graph: typeof import('./../components/graph/Graph.vue')['default']
    GraphElementList: typeof import('./../components/graph/GraphElementList.vue')['default']
    GraphElementListCard: typeof import('./../components/graph/GraphElementListCard.vue')['default']
    GraphLegend: typeof import('./../components/graph/GraphLegend.vue')['default']
    GraphSelectedInfo: typeof import('./../components/graph/GraphSelectedInfo.vue')['default']
    HeatMap: typeof import('./../components/clustering/HeatMap.vue')['default']
    InfoDot: typeof import('./../components/InfoDot.vue')['default']
    LabelDot: typeof import('./../components/LabelDot.vue')['default']
    LabelsTable: typeof import('./../components/LabelsTable.vue')['default']
    LabelText: typeof import('./../components/LabelText.vue')['default']
    Loading: typeof import('./../components/Loading.vue')['default']
    OverviewBarchart: typeof import('./../components/overview/OverviewBarchart.vue')['default']
    PairCodeDiff: typeof import('./../components/pair/PairCodeDiff.vue')['default']
    PairCodeFileInfo: typeof import('./../components/pair/PairCodeFileInfo.vue')['default']
    PairCodeMatch: typeof import('./../components/pair/PairCodeMatch.vue')['default']
    PairCodeMatchEditor: typeof import('./../components/pair/PairCodeMatchEditor.vue')['default']
    PairsTable: typeof import('./../components/pair/PairsTable.vue')['default']
    PairStatHistogram: typeof import('./../components/summary/PairStatHistogram.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimilarityDisplay: typeof import('./../components/SimilarityDisplay.vue')['default']
    SimilaritySetting: typeof import('./../components/settings/SimilaritySetting.vue')['default']
    SubmissionCard: typeof import('./../components/submission/SubmissionCard.vue')['default']
    SubmissionCode: typeof import('./../components/submission/SubmissionCode.vue')['default']
    SubmissionsPairsTable: typeof import('./../components/submission/SubmissionsPairsTable.vue')['default']
    SubmissionsTable: typeof import('./../components/submission/SubmissionsTable.vue')['default']
    TimeSeries: typeof import('./../components/clustering/TimeSeries.vue')['default']
  }
}
