/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./../components/Breadcrumbs.vue')['default']
    ClusterHeatMap: typeof import('./../components/clustering/ClusterHeatMap.vue')['default']
    ClustersTable: typeof import('./../components/clustering/ClustersTable.vue')['default']
    ClusterTags: typeof import('./../components/clustering/ClusterTags.vue')['default']
    ClusterTimeSeries: typeof import('./../components/clustering/ClusterTimeSeries.vue')['default']
    CompareCard: typeof import('./../components/CompareCard.vue')['default']
    FileTimestamp: typeof import('./../components/FileTimestamp.vue')['default']
    GraphCanvas: typeof import('./../components/graph/GraphCanvas.vue')['default']
    GraphElementList: typeof import('./../components/graph/GraphElementList.vue')['default']
    GraphElementListCard: typeof import('./../components/graph/GraphElementListCard.vue')['default']
    GraphLegend: typeof import('./../components/graph/GraphLegend.vue')['default']
    GraphSelectedInfo: typeof import('./../components/graph/GraphSelectedInfo.vue')['default']
    InfoDot: typeof import('./../components/InfoDot.vue')['default']
    LabelDot: typeof import('./../components/LabelDot.vue')['default']
    LabelsTable: typeof import('./../components/LabelsTable.vue')['default']
    LabelText: typeof import('./../components/LabelText.vue')['default']
    PageError: typeof import('./../components/layout/PageError.vue')['default']
    PageLoading: typeof import('./../components/layout/PageLoading.vue')['default']
    PageNavbar: typeof import('./../components/layout/PageNavbar.vue')['default']
    PageSettings: typeof import('./../components/layout/PageSettings.vue')['default']
    PageSidebar: typeof import('./../components/layout/PageSidebar.vue')['default']
    PairCodeDiff: typeof import('./../components/pair/PairCodeDiff.vue')['default']
    PairCodeFileInfo: typeof import('./../components/pair/PairCodeFileInfo.vue')['default']
    PairCodeMatch: typeof import('./../components/pair/PairCodeMatch.vue')['default']
    PairCodeMatchEditor: typeof import('./../components/pair/PairCodeMatchEditor.vue')['default']
    PairsTable: typeof import('./../components/pair/PairsTable.vue')['default']
    QuestionnaireAlert: typeof import('./../components/QuestionnaireAlert.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimilarityDisplay: typeof import('./../components/SimilarityDisplay.vue')['default']
    SimilarityHistogram: typeof import('./../components/SimilarityHistogram.vue')['default']
    SimilaritySetting: typeof import('./../components/settings/SimilaritySetting.vue')['default']
    Snackbar: typeof import('./../components/util/snackbar/Snackbar.vue')['default']
    SubmissionCard: typeof import('./../components/submission/SubmissionCard.vue')['default']
    SubmissionCode: typeof import('./../components/submission/SubmissionCode.vue')['default']
    SubmissionHistogram: typeof import('./../components/submission/SubmissionHistogram.vue')['default']
    SubmissionsPairsTable: typeof import('./../components/submission/SubmissionsPairsTable.vue')['default']
    SubmissionsTable: typeof import('./../components/submission/SubmissionsTable.vue')['default']
    SurveyAlert: typeof import('./../components/SurveyAlert.vue')['default']
    UploadFormCard: typeof import('./../components/upload/UploadFormCard.vue')['default']
    UploadInput: typeof import('./../components/upload/UploadInput.vue')['default']
    UploadsTable: typeof import('./../components/upload/UploadsTable.vue')['default']
    UploadsTableDeleteDialog: typeof import('./../components/upload/UploadsTableDeleteDialog.vue')['default']
    UploadsTableInfoDialog: typeof import('./../components/upload/UploadsTableInfoDialog.vue')['default']
    UploadsTableShareDialog: typeof import('./../components/upload/UploadsTableShareDialog.vue')['default']
    UploadStatus: typeof import('./../components/upload/UploadStatus.vue')['default']
  }
}
