// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Breadcrumbs: typeof import("./../components/Breadcrumbs.vue")["default"]
    ClusteringCard: typeof import("./../components/clustering/ClusteringCard.vue")["default"]
    ClusteringTable: typeof import("./../components/ClusteringTable.vue")["default"]
    CompareCard: typeof import("./../components/CompareCard.vue")["default"]
    CompareSide: typeof import("./../components/CompareSide.vue")["default"]
    FileTagList: typeof import("./../components/clustering/FileTagList.vue")["default"]
    FileTimestamp: typeof import("./../components/FileTimestamp.vue")["default"]
    Graph: typeof import("./../components/graph/Graph.vue")["default"]
    GraphElementList: typeof import("./../components/GraphElementList.vue")["default"]
    GraphElementListCard: typeof import("./../components/GraphElementListCard.vue")["default"]
    GraphLegend: typeof import("./../components/GraphLegend.vue")["default"]
    GraphSelectedInfo: typeof import("./../components/GraphSelectedInfo.vue")["default"]
    GraphTab: typeof import("./../components/clustering/GraphTab.vue")["default"]
    HeatMap: typeof import("./../components/clustering/HeatMap.vue")["default"]
    InfoDot: typeof import("./../components/InfoDot.vue")["default"]
    LabelDot: typeof import("./../components/LabelDot.vue")["default"]
    LabelsTable: typeof import("./../components/LabelsTable.vue")["default"]
    LabelText: typeof import("./../components/LabelText.vue")["default"]
    Loading: typeof import("./../components/Loading.vue")["default"]
    OverviewBarchart: typeof import("./../components/overview/OverviewBarchart.vue")["default"]
    PairCodeDiff: typeof import("./../components/pair/PairCodeDiff.vue")["default"]
    PairCodeFileInfo: typeof import("./../components/pair/PairCodeFileInfo.vue")["default"]
    PairCodeMatch: typeof import("./../components/pair/PairCodeMatch.vue")["default"]
    PairCodeMatchEditor: typeof import("./../components/pair/PairCodeMatchEditor.vue")["default"]
    PairsTable: typeof import("./../components/PairsTable.vue")["default"]
    PairStatHistogram: typeof import("./../components/summary/PairStatHistogram.vue")["default"]
    RouterLink: typeof import("vue-router")["RouterLink"]
    RouterView: typeof import("vue-router")["RouterView"]
    SemanticList: typeof import("./../components/SemanticList.vue")["default"]
    SimilarityDisplay: typeof import("./../components/pair/SimilarityDisplay.vue")["default"]
    SimilaritySetting: typeof import("./../components/settings/SimilaritySetting.vue")["default"]
    SubmissionCard: typeof import("./../components/SubmissionCard.vue")["default"]
    SubmissionCode: typeof import("./../components/SubmissionCode.vue")["default"]
    SubmissionsPairsTable: typeof import("./../components/SubmissionsPairsTable.vue")["default"]
    SubmissionsTable: typeof import("./../components/SubmissionsTable.vue")["default"]
    TimeSeries: typeof import("./../components/clustering/TimeSeries.vue")["default"]
    TimeSeriesCard: typeof import("./../components/clustering/TimeSeriesCard.vue")["default"]
  }
}
