FROM node:22.17.1-alpine3.21

WORKDIR /repo/

RUN apk add --no-cache curl

ADD package-lock.json package.json /repo/
ADD core/ /repo/core
ADD web/ /repo/web

RUN npm install


ENV VITE_HOST=0.0.0.0
ENV VITE_PORT=8080
ENV VITE_MODE=server
ENV DEFAULT_VITE_API_URL=http://localhost:3000
EXPOSE 8080/tcp

WORKDIR /repo/web

RUN VITE_API_URL="$DEFAULT_VITE_API_URL" npm run build


SHELL ["/bin/sh", "-c"]

CMD (test "$VITE_API_URL" == "$DEFAULT_VITE_API_URL" || npm run build) && npm run preview -- --host "$VITE_HOST" --port "$VITE_PORT" --strictPort
