FROM node:22.17.1-alpine3.22

WORKDIR /repo/

RUN apk add --no-cache curl

ADD package-lock.json package.json tsconfig.global.json /repo/
ADD core/ /repo/core

ADD web/index.d.ts web/index.js web/index.html web/package.json web/tsconfig.json web/vite.config.ts web/tsconfig.node.json /repo/web/
ADD web/src /repo/web/src
ADD web/public /repo/web/public

RUN npm install
RUN npm run build --workspace core

ENV VITE_HOST=0.0.0.0
ENV VITE_PORT=8080
ENV VITE_MODE=server
ENV DEFAULT_VITE_API_URL=http://localhost:3000
EXPOSE 8080/tcp

WORKDIR /repo/web

RUN VITE_API_URL="$DEFAULT_VITE_API_URL" npm run build


SHELL ["/bin/sh", "-c"]

CMD (test "$VITE_API_URL" == "$DEFAULT_VITE_API_URL" || npm run build) && npm run preview -- --host "$VITE_HOST" --port "$VITE_PORT" --strictPort
