source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.6'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 8.0.2'

# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5', '>= 0.5.6'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 6.6'

# Process ZIP archives
gem 'rubyzip', '~> 2.4.1'

# Validate ActiveStorage attachments
gem 'active_storage_validations', '~> 1.4'

# interfacing with docker
gem 'docker-api', '~> 2.4.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Delayed Job for background jobs
gem 'delayed_job_active_record'

# CORS middleware
gem 'rack-cors'

# Use ActiveModelSerializer for serializing to JSON
gem 'active_model_serializers', '~> 0.10', '>= 0.10.15'

# Use Sentry
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'stackprof'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mingw x64_mingw]

  # Factory bot for testing factories
  gem 'factory_bot_rails', '~> 6.5.0'

  # Faker for generating test data
  gem 'faker', '~> 3.5.2'

  # Stubbing and mocking
  gem 'mocha', '~> 2.7.1'
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
  gem 'annotaterb', '~> 4.17' # Remove workaround in lib/tasks/annotate.rb when https://github.com/ctran/annotate_models/issues/696 is fixed
  gem 'rubocop-minitest', '~> 0.36.0'
  gem 'rubocop-rails', '~> 2.30', '>= 2.30.3'
end

# Use Capistrano for deployment
gem 'capistrano', '~> 3.19', '>= 3.19.2', group: :development
gem 'capistrano3-delayed-job', '~> 1.7.6'
gem 'capistrano-passenger', '~> 0.2.1', group: :development
gem 'capistrano-rails', '~> 1.7.0', group: :development
gem 'capistrano-rvm', '~> 0.1.2', group: :development
gem 'capistrano-yarn', '~> 2.0.2'

# Needed to support ecc keys
gem 'bcrypt_pbkdf'
gem 'ed25519'
